[package]
name = "fluvio-wasm-filter-random-sample"
version = "0.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
once_cell = "1.13.0"
fastrand = "1.8.0"
fluvio-smartmodule = { workspace = true }
