[package]
name = "fluvio-benchmark"
version = "0.0.0"
edition = "2021"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio benchmarking tool"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"
publish = false

[dependencies]
async-std = "1.12.0"
bincode = "1.3.3"
clap = { version = "4.0.9", features = ["derive"] }
hdrhistogram = "7.5.2"
tracing = "0.1.26"
pad = "0.1.6"
rand = "0.8.5"
serde = { version = "1.0.103", features = ['derive'] }
serde_yaml = "0.8"
statrs = "0.16.0"
walkdir = "2.3.2"


fluvio = { path = "../fluvio" }
fluvio-future = { version = "0.4.0", features = ['subscriber'] }
