[package]
name = "fluvio-benchmark"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluvio = { path = "../fluvio" }


async-std = "1.12.0"
criterion = { version = "0.4.0", features = ["async", "async_std"] }


[[bench]]
name = "producer_consumer"
harness = false
