[package]
name = "fluvio-benchmark"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluvio = { path = "../fluvio" }

async-std = "1.12.0"
clap = { version = "4.0.9", features = ["derive"] }
criterion = { version = "0.4.0", features = ["async", "async_std"] }
env_logger = "0.9.3"
hdrhistogram = "7.5.2"
log = "0.4.17"
pad = "0.1.6"
rand = "0.8.5"
serde = { version = "1.0.103", features = ['derive'] }
serde_yaml = "0.8"
statrs = "0.16.0"
walkdir = "2.3.2"
